dependencies:
  flutter:
    sdk: flutter
  bonsoir: ^5.0.0      # لاكتشاف الأجهزة على الشبكة المحلية
  shelf: ^1.4.1        # لعمل سيرفر خفيف جداً جوه الموبايل للمضيف
  shelf_router: ^1.1.4 # لتنظيم طلبات السيرفر
  http: ^1.2.0         # لإرسال الطلبات بين اللاعبين
