name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 1. إنشاء ملفات منصة الأندرويد المفقودة فقط دون مسح ملفات الكود
      - name: Generate Android Folder
        run: flutter create . --platforms=android --org com.imposter.alive

      # 2. تحميل المكتبات
      - name: Get Dependencies
        run: flutter pub get

      # 3. بناء الـ APK مباشرة من ملف اللعبة الأصلي
      - name: Build Release APK
        run: flutter build apk --release -t lib/main.dart --no-tree-shake-icons

      # 4. رفع ملف اللعبة الجاهز
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Imposter-Alive-APK
          path: build/app/outputs/flutter-apk/app-release.apk
